version: '3'
services:
  server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_SERVERS=mongo-rs0-1:27017,mongo-rs0-2:27017,mongo-rs0-3:27017
      - DEBUG=crowd-sourcing:*
      - NODE_ENV=local
#    volumes:
#      - ./lib:/lib
    networks:
      - app_net
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_net
networks:
  app_net:
    external:
      name: app_net